# Generated by Django 3.2.6 on 2021-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_feedback_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
