# Generated by Django 3.2.6 on 2021-08-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_comments_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
