# Generated by Django 3.2.6 on 2021-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0022_auto_20200511_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
