# Generated by Django 3.2.6 on 2021-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_delete_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
